### ISSUE TITLE
Add support for building image on an aarch64 host machine

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#193]
This is potentially something we are considering for a future release.

**Comment by e-minguez** [comment]
related #68

**Comment by orangedeng** [comment]
Just FYI on this
ISO build success in ubuntu:22.04, aarch64, aws with manual eib built binary.

**Comment by orangedeng** [comment]
There are two problem to run EIB on aarch64:

1. qemu-ipxe must be installed in aarch64. Then guestfish can detect the kvm disabled state.
2. As guestfish requires https://github.com/libguestfs/libguestfs/blob/master/generator/UEFI.ml#L67-L77
```
    "aarch64",
    "/usr/share/AAVMF/AAVMF_CODE.fd",
    Some "/usr/share/AAVMF/AAVMF_CODE.verbose.fd",
    "/usr/share/AAVMF/AAVMF_VARS.fd",
    [];

    "aarch64",
    "/usr/share/edk2/aarch64/QEMU_EFI-pflash.raw",
    None,
    "/usr/share/edk2/aarch64/vars-template-pflash.raw",
    [];
```
  
efi device is required for booting aarch64 vm via qemu-system-aarch64. Which can't be found in opensuse/sles 15.5 packages.
In the ubuntu 22.04, The efi device can be installed by `qemu-efi-aarch64`.

**Comment by orangedeng** [comment]
Marking a aarch working Dockerfile for EIB here: https://github.com/orangedeng/edge-image-builder/blob/add-aarch-build-dockerfile/Dockerfile.arm

There are some problems while the ISO got built:
- OS level, guestfish virtual-tar-out has proformance problem, It takes 20-30 mins to run parsing VM disk to container image. Using machine spec AWS `c6g.2xlarge`. It only use 1 core so `tar -C /sysroot/ -cf - .` takes forever to process.
- Kubernetes/K3s: downloaded wrong arch airgap package, amd64 instead of arm64
- registry: downloaded wrong arch images, amd64 instead of arm64.(hauler binary is fine)

Hope the information above can help.
