### ISSUE TITLE
Productize the EIB runtime container

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#21]
When the raw image support was first added (https://github.com/suse-edge/edge-image-builder/pull/18), the EIB image itself was changed from bci-base to openSUSE Leap. The driving reason was the sheer amount of dependencies that need to be installed for the raw support. 

For development purposes, this absolutely works. But we need to revisit whether or not we want to refine the build into a builder image and copying just the necessary binaries into a BCI base image.

**Comment by atanasdinov** [comment]
All dependencies are now installed as RPMs (e.g. helm, Hauler, nmc).

It is indeed possible to copy the resulting binaries of most RPM installations, however, this is not easily achievable for the RAW image modification dependencies which install multiple binaries, libraries and additional files:
- libguestfs, kernel-default, e2fsprogs, parted, gptfdisk, btrfsprogs, guestfs-tools, lvm2

Using `opensuse/leap` images is not only completely fine but necessary due to its compatibility with SLE-based packages as well as the zypper availability. Its size is also small enough (even smaller than bci-base).

All dependencies have also been verified to be required and we're currently unable to drop any.

Closing as completed.
