### ISSUE TITLE
Use kube-system namespace to host the helmcharts instead

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#324]
On RKE2 https://docs.rke2.io/helm#using-the-helm-crd the charts by default use the kube-system namespace instead of the 'default' one
![image](https://github.com/suse-edge/edge-image-builder/assets/346758/df245b3a-cbd4-417a-b110-69805025ecbb)

I guess we should do the same here.

**Comment by atanasdinov** [comment]
This is yet another intentional design decision. The core charts which EIB installs use `kube-system` [by default](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/helm.go#L13), however, it's up to the users to specify the `installationNamespace` they prefer for their charts.
