### ISSUE TITLE
RPM resolve issue

### ISSUE THREAD

**Issue by nqerz** [suse-edge/edge-image-builder#327]
I am using the latest main branch code to build EIB tools, and use yaml to define packages and run eib build but it encountered a network problems log error messages:
`Announcing system to https://scc.suse.com/ ...[0m
SUSEConnect error: Post "[https://scc.suse.com/connect/subscriptions/systems"](https://scc.suse.com/connect/subscriptions/systems%22): dial tcp 18.158.201.163:443: i/o timeout`

It may caused by we use an proxy (env https_proxy) to connect to external resource, but the EIB tool do not have any proxy settings, is any workaround for this kind of building environment?

**Comment by e-minguez** [comment]
I'm not sure this will work but can you try passing all the proxy env vars to the podman run command?
`podman run -it --rm -e HTTP_PROXY=...` (for all the proxy vars as well as the lowercase versions of those)

**Comment by atanasdinov** [comment]
Hello, @nqerz! Thanks for raising this.

Could you please provide the following in order to better understand the problem:
- definition file (feel free to edit away the sensitive information)
- all log files related to the [RPM dependency resolution](https://github.com/suse-edge/edge-image-builder/blob/main/docs/debugging.md#rpm-dependency-resolution)
